"""
Build knowledge_base/index.md — a flat index of every article, grouped by
category, that both Search and Ask modes rely on.

Each article is a markdown file with YAML frontmatter:

    ---
    summary: "One sentence describing what this article covers."
    category: "Billing / Payments"        # optional; "/" creates a sub-group
    tags: "refund, credit, chargeback"     # optional, search-only hints
    url: "https://help.example.com/refunds" # optional canonical link
    ---

Run from the project root:
    python scripts/build_index.py
"""

import re
import sys
from pathlib import Path
from collections import defaultdict

# Allow overriding the knowledge base location: build_index.py [KB_PATH]
KB_ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else (Path(__file__).resolve().parent.parent / "knowledge_base")
ARTICLES_DIR = KB_ROOT / "articles"
OUTPUT = KB_ROOT / "index.md"


def parse_frontmatter(text: str) -> dict:
    """Extract YAML frontmatter as a flat dict of string values."""
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}
    result = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            result[key.strip()] = val.strip().strip('"').strip("'")
    return result


def collect_articles() -> list[dict]:
    articles = []
    for path in sorted(ARTICLES_DIR.rglob("*.md")):
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        fm = parse_frontmatter(text)
        articles.append({
            "path": path.relative_to(KB_ROOT).as_posix(),
            "summary": fm.get("summary", "").strip(),
            "category": fm.get("category", "Uncategorized").strip() or "Uncategorized",
            "tags": fm.get("tags", "").strip(),
        })
    return articles


def group_by_category(articles: list[dict]) -> dict:
    groups: dict[str, list] = defaultdict(list)
    for a in articles:
        groups[a["category"]].append(a)
    return dict(sorted(groups.items()))


def render_index(groups: dict) -> str:
    lines = [
        "# Article index",
        "",
        "_Generated by scripts/build_index.py — do not edit by hand._",
        "_Find the relevant article by summary, then read it with `read_file`._",
        "",
        "---",
        "",
    ]

    current_top = None
    for category, articles in groups.items():
        top = category.split(" / ")[0]
        if top != current_top:
            if current_top is not None:
                lines += ["", "---", ""]
            lines += [f"## {top}", ""]
            current_top = top

        sub = category.partition(" / ")[2]
        if sub:
            lines += [f"### {sub}", ""]

        for a in articles:
            summary = a["summary"] or "*(no summary)*"
            tail = f" | {a['tags']}" if a["tags"] else ""
            lines.append(f"- `{a['path']}` — {summary}{tail}")
        lines.append("")

    return "\n".join(lines)


def main():
    if not ARTICLES_DIR.is_dir():
        print(f"No articles directory found at: {ARTICLES_DIR}")
        sys.exit(1)
    articles = collect_articles()
    groups = group_by_category(articles)
    OUTPUT.write_text(render_index(groups), encoding="utf-8")
    print(f"Wrote {len(articles)} articles across {len(groups)} categories -> {OUTPUT}")
    print(f"File size: {OUTPUT.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
